mail_django/base/urls.py
from django.urls import path
from mail_django.base import views
app_name = 'base'
urlpatterns = [
    path('', views.home, name='home'),
    path('logado/', views.logado, name='logado'),

]

mail_django/mail_register/urls.py
from django.urls import path
from mail_django.mail_register import views
app_name = 'mail_register'
urlpatterns = [
    path('', views.mail, name='mail')
]

mail_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('django.contrib.auth.urls')),
    path('', include('mail_django.base.urls')),
    path('mail/', include('mail_django.mail_register.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

mail_django/base/models.py
from django.apps import apps  # used in GlobalUserModel in UserManager class
from django.contrib import auth
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        username = GlobalUserModel.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)

    def with_perm(self, perm, is_active=True, include_superusers=True, backend=None, obj=None):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    'You have multiple authentication backends configured and '
                    'therefore must provide the `backend` argument.'
                )
        elif not isinstance(backend, str):
            raise TypeError(
                'backend must be a dotted import path string (got %r).'
                % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, 'with_perm'):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


class User(AbstractBaseUser, PermissionsMixin):
    """
    App Base - User Class
    Username, e-mail and password are required.
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    # first_name = models.CharField(_('first name'), max_length=150, blank=True)
    # last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True, error_messages={
            'unique': _("A user with that e-mail already exists."),
        }, )

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    # def get_full_name(self):
    #     """
    #     Return the first_name plus the last_name, with a space in between.
    #     """
    #     full_name = '%s %s' % (self.first_name, self.last_name)
    #     return full_name.strip()

    # def get_short_name(self):
    #     """Return the short name for the user."""
    #     return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

mail_django/mail_register/models.py
# from django.db import models

# Create your models here.

mail_django/base/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')


def logado(request):
    return HttpResponse('vc esta logado')

mail_django/mail_register/views.py
# from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


@login_required
def mail(request):
    return HttpResponse("this is register.")

mail_django/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django Email{% endblock title %}</title>
    <meta name="description" content="{% block description %}Demo Django{% endblock description %}">
    <meta name="author" content="Pedro Madureira">

    <link rel="icon" type="image/jpg" href="{% static 'img/favicon.jpg' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</head>
<body>
<!-- Nav bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'base:home' %}">Email Django</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>

        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            </ul>
        </div>
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    {{user.first_name}}
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <div class="dropdown-item">
                        <a class="btn btn-danger" href="{% url 'logout' %}">Sair</a>
                    </div>
                </div>
            </li>
        </ul>
        {% else %}
        <a class="btn btn-light my-2" href="{% url 'login' %}">Entrar</a>
        {% endif %}
    </div>
    <!-- Fim da nav bar -->
</nav>
<!-- Body -->
{% block body %}{% endblock body %}
<!-- Fim do body -->
<!-- footer-->
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Entre em Contato</h3>
                <address>
                    62 99337-8753
                    <br/>
                    <a href="mailto:contato@phsolucoesweb.com.br" class="text-light">contato@phsolucoesweb.com.br</a>
                </address>
            </div>
        </div>

    </div>
    <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} PH - Soluções Web.
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Fim do footer -->

</body>
</html>

mail_django/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Mail Django - Home{% endblock title %}
{% block description %}Plataforma Django para envio de e-mail com pdf anexado{% endblock description %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2>
                    Django Email
                </h2>
                <p>
                    Demonstração de aplicação Django com envio de e-mails.
                </p>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <h5 class="card-header">
                            Framework Web Utilizado
                        </h5>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/django.png' %}" alt="Imagem do django" class="img-thumbnail
                                float-left m-3"/>
                                Django é um framework para desenvolvimento rápido para web, escrito em Python, que
                                utiliza o padrão model-template-view (MTV).
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body%}